### ISSUE TITLE
Tracking issue stable MVP release

### ISSUE THREAD

**Issue by cbourjau** [Quantco/spox#15]
We cannot use steelix in production until we have settled on a semver-stable API. This is pretty sad since that means using `skl2onnx` in the meantime. I therefore want to get a stable release of `steelix` out of the door as quickly as possible. On the other hand, I don't want to limit design space by prematurely stabilizing things that we have not yet gathered experience with. I would like to settle on an solid MVP upon which we can then build and extend after having introduced steelix into production. To that end, we ought to:
- [x] Settle on a non-IPed library name asap
- [x] Resolve naming questions (namely `Arrow`, `arguments`, `results`. Any others?)
- [x] Make **everything** private for now which is not immediately needed for converters in `quantcore.learn` or downstream projects. 

The last point requires a bit more details. A working MVP must be able to create `Arrow`s (or whatever they will be called next week), use the constructors from the generated opset and tie everything together into a `ModelProto`. This should be the MVP. I am not happy yet with our `Node`, build system and how we handle ONNX functions. I therefore don't want to expose/stabilize:
- Anything related to functions. This has no impact on the user since functions are quite broken in the ORT anyhow.
- Anything to do with nodes (Attributes, Inputs, Outputs, Arrowfields, ...) I am aware that this would mean that a user is not able to write custom constructor functions with the MVP but I think that is preferable to stabilizing some of the core implementation details of steelix today.
- Operator overloads

Two other notable classes that must be in the public API are `steelix.type_system.Type` and at least `Tensor` (could we get away with not stabilizing `Sequence`, `Map`, `Optional`?) if we stick with the current design of having `Arrow` cover all those types (see Quantco/spox-foss#11 ).

Did you come across a use-case, @JanJaguschQC , which would not be covered by the above MVP today?
