### ISSUE TITLE
Tracking issue for full-feature inline

### ISSUE THREAD

**Issue by jbachurski** [Quantco/spox#82]
`inline` is currently missing:

- [ ] Support for subgraphs (they should get prefixed properly, which ONNX renaming doesn't do)
- [ ] Support for functions (such local/dependency functions should be propagated to the built model)
- [ ] Capability not do add extraneous Identity nodes for all model input/outputs (requires better renaming capabilties)

Most of these can be fixed by reimplementing renaming values in graphs, as the ONNX feature is rather lacking.
